## Lists as Arrays

In [1]:
a = [1, "Hello", [3.14, "world"]]
a.append(2)  # Add an integer to the end
print(a)

[1, 'Hello', [3.14, 'world'], 2]


## NumPy Arrays

In [2]:
import numpy as np

# create a numpy array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

# elementwise operations
print(arr*2)

# multidimension array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[1 2 3 4 5]
[ 2  4  6  8 10]
[[1 2 3]
 [4 5 6]]


## Python Arrays

In [3]:
import array as arr
a = arr.array('i', [1, 2, 3])
print(a)
#

array('i', [1, 2, 3])


## Accessing Array Items

In [4]:
import array as arr
a = arr.array('i', [1, 2, 3, 4, 5, 6])

print(a[0])
print(a[3])

b = arr.array('d', [2.5, 3.2, 3.3])
print(b[1])
print(b[2])

1
4
3.2
3.3


## Removing Elements from the Array


In [5]:
import array
arr = array.array('i', [1, 2, 3, 1, 5])

# using remove() method to remove first occurance of 1
arr.remove(1)
print(arr)

# pop() method - remove item at index 2
arr.pop(2)
print(arr)

array('i', [2, 3, 1, 5])
array('i', [2, 3, 5])


## Slicing of an Array

In [6]:
import array as arr
l = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

a = arr.array('i', l)


Sliced_array = a[3:8]
print(Sliced_array)

Sliced_array = a[5:]
print(Sliced_array)

Sliced_array = a[:]
print(Sliced_array)

array('i', [4, 5, 6, 7, 8])
array('i', [6, 7, 8, 9, 10])
array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])


## Searching Element in an Array


In [7]:
import array
arr = array.array('i', [1, 2, 3, 1, 2, 5])

# index of 1st occurrence of 2
print(arr.index(2))

# index of 1st occurrence of 1
print(arr.index(1))

1
0


## Updating Elements in an Array

In [8]:
import array
arr = array.array('i', [1, 2, 3, 1, 2, 5])

# update item at index 2
arr[2] = 6
print(arr)

# update item at index 4
arr[4] = 8
print(arr)

array('i', [1, 2, 6, 1, 2, 5])
array('i', [1, 2, 6, 1, 8, 5])


## Different Operations on Python Arrays


### 1. Counting Elements in an Array


In [9]:
import array

arr = array.array('i', [1, 2, 3, 4, 2, 5, 2])
count = arr.count(2)

print("Number of occurrences of 2:", count)

Number of occurrences of 2: 3


### 3. Reversing Elements in an Array


In [10]:
import array
arr = array.array('i', [1, 2, 3, 4, 5])

arr.reverse()
print("Reversed array:", *arr)

Reversed array: 5 4 3 2 1
